apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sluice.name" . }}
  labels:
    {{- include "sluice.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sluice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sluice.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.port }}"
        prometheus.io/path: "/metrics"
        checksum/config: {{ .Values.config | toYaml | sha256sum }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      containers:
        - name: sluice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["serve", "--config", "/etc/sluice/config.yaml"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          envFrom:
            - secretRef:
                name: {{ include "sluice.name" . }}-secrets
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 3
          readinessProbe:
            httpGet: { path: /readyz, port: http }
            initialDelaySeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/sluice
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "sluice.name" . }}-config
